=== TvrtkoTomic/otvrac_lab/json_schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://example.com/example.json",
    "type": "array",
    "default": [],
    "title": "Dućani tehnike",
    "description": "JSON koji sadrži neke dućane tehnike i podatke vezane uz njih, kao naziv, adresa, vlasnik....",
    "items": {
        "type": "object",
        "description": "Jedan redak iz baze,",
        "required": [
            "naziv",
            "adresa",
            "grad",
            "drzava",
            "telefonski_broj",
            "email",
            "geolokacija",
            "recenzija",
            "postanski_broj",
            "vlasnici"
        ],
        "properties": {
            "naziv": {
                "type": "string",
                "title": "naziv",
                "description": "naziv dućana",
                "examples": [
                    "Emmezeta",
                    "Svijet medija",
                    "Elipso",
                    "Links.hr",
                    "Laptopi.hr",
                    "Saturn",
                    "Instar",
                    "Sancta Domenica",
                    "HGSPOT"
                ]
            },
            "adresa": {
                "type": "string",
                "title": "adresa",
                "description": "Adresa dućana",
                "examples": [
                    "Ulica Siniše Glavaševića 1",
                    "Trg Drage Iblera 10",
                    "Ulica Rudolfa Kolaka 14",
                    "Dankovečka ulica 5",
                    "Dugoselska ulica 12",
                    "Alexanderplatz 3",
                    "Ulica Josipa Jovića 93",
                    "Vukovarska ulica 207",
                    "Užarska ulica 18"
                ]
            },
            "grad": {
                "type": "string",
                "title": "grad",
                "description": "Grad u kojem se dućan nalazi",
                "examples": [
                    "Zagreb",
                    "Berlin",
                    "Split",
                    "Rijeka"
                ]
            },
            "drzava": {
                "type": "string",
                "title": "drzava",
                "description": "Država u kojoj se nalazi dućan",
                "examples": [
                    "Hrvatska",
                    "Njemačka"
                ]
            },
            "telefonski_broj": {
                "type": "integer",
                "title": "telefonski broj",
                "description": "Telefonski broj dućana",
                "examples": [
                    "072202022",
                    "014554882",
                    "015533094",
                    "013096944",
                    "016182261",
                    "4922122243333",
                    "021440214",
                    "072336955",
                    "051317475"
                ]
            },
            "email": {
                "type": "string",
                "title": "email",
                "description": "email dućana za kontakt",
                "examples": [
                    "info@emmezeta.hr",
                    "importanne.galleria@svijet-medija.hr",
                    "podrska@links.hr",
                    " dubrava@links.hr",
                    "prodaja@pc1.hr",
                    "shop@saturn.de",
                    "split@instar-informatika.hr",
                    "podrska@sancta-domenica.hr",
                    "rijeka@hgspot.hr"
                ]
            },
            "geolokacija": {
                "type": "string",
                "title": "geolokacija",
                "description": "Geolokacija dućana u koordinatama",
                "examples": [
                    "45.80, 16.05",
                    "45.85, 16.00",
                    "45.84, 16.05",
                    "45.83, 16.06",
                    "45.80, 16.02",
                    "52.52, 13.41",
                    "43.61, 16.48",
                    "43.51, 16.50",
                    "45.51, 14.42"
                ]
            },
            "recenzija": {
                "type": "number",
                "title": "recenzija",
                "description": "Ocjene dućana s Google Maps",
                "examples": [
                    4.3,
                    4.1,
                    4.4,
                    2.8,
                    4.2,
                    4.6
                ]
            },
            "postanski_broj": {
                "type": "integer",
                "title": "postanski broj",
                "description": "Poštanski broj dućana",
                "examples": [
                    "10000",
                    "10040 ",
                    "10000 ",
                    "10178",
                    "21000",
                    "51000"
                ]
            },
            "vlasnici": {
                "type": "array",
                "title": "vlasnici",
                "description": "Skup vlasnika dućana, može biti 1 ili više",
                "items": {
                    "type": "object",
                    "title": "vlasnik",
                    "description": "Instanca vlasnika, može ih biti 1 ili više",
                    "required": [
                        "ime",
                        "prezime"
                    ],
                    "properties": {
                        "ime": {
                            "type": "string",
                            "title": "ime",
                            "description": "Ime vlasnika",
                            "examples": [
                                "Andrzej",
                                "Anđelko",
                                "Bernard",
                                "Denis",
                                "Vedran",
                                "Emil",
                                "Karsten",
                                "Marko",
                                "Robert ",
                                "Saša"
                            ]
                        },
                        "prezime": {
                            "type": "string",
                            "title": "ime",
                            "description": "Prezime vlasnika",
                            "examples": [
                                "Pawel Sitarz",
                                "Ćurić",
                                "Šepetanc",
                                "Piljek",
                                "Puškarić",
                                "Bogdan",
                                "Wildberger",
                                "Cvetovski",
                                "Škeljo",
                                "Lončar"
                            ]
                        }
                    }
                }
                    
                
                
            }
        }
    }
       
}

=== TvrtkoTomic/otvrac_lab/Release 1.0/ducani_tehnike.json
[
  {
    "naziv": "Links.hr",
    "adresa": "Dankovečka ulica 5",
    "grad": "Zagreb",
    "drzava": "Hrvatska",
    "telefonski_broj": 13096944,
    "email": " dubrava@links.hr",
    "geolokacija": "45.83, 16.06",
    "recenzija": 4.4,
    "postanski_broj": 10040,
    "vlasnici": [
      {
        "ime": "Vedran",
        "prezime": "Puškarić"
      },
      {
        "ime": "Denis",
        "prezime": "Piljek"
      }
    ]
  },
  {
    "naziv": "Elipso",
    "adresa": "Ulica Rudolfa Kolaka 14",
    "grad": "Zagreb",
    "drzava": "Hrvatska",
    "telefonski_broj": 15533094,
    "email": "podrska@links.hr",
    "geolokacija": "45.84, 16.05",
    "recenzija": 4.1,
    "postanski_broj": 10040,
    "vlasnici": [
      {
        "ime": "Bernard",
        "prezime": "Šepetanc"
      }
    ]
  },
  {
    "naziv": "Laptopi.hr",
    "adresa": "Dugoselska ulica 12",
    "grad": "Zagreb",
    "drzava": "Hrvatska",
    "telefonski_broj": 16182261,
    "email": "prodaja@pc1.hr",
    "geolokacija": "45.80, 16.02",
    "recenzija": 2.8,
    "postanski_broj": 10000,
    "vlasnici": [
      {
        "ime": "Emil",
        "prezime": "Bogdan"
      }
    ]
  },
  {
    "naziv": "Sancta Domenica",
    "adresa": "Vukovarska ulica 207",
    "grad": "Split",
    "drzava": "Hrvatska",
    "telefonski_broj": 72336955,
    "email": "podrska@sancta-domenica.hr",
    "geolokacija": "43.51, 16.50",
    "recenzija": 4.4,
    "postanski_broj": 21000,
    "vlasnici": [
      {
        "ime": "Robert",
        "prezime": "Škeljo"
      }
    ]
  },
  {
    "naziv": "Instar",
    "adresa": "Ulica Josipa Jovića 93",
    "grad": "Split",
    "drzava": "Hrvatska",
    "telefonski_broj": 21440214,
    "email": "split@instar-informatika.hr",
    "geolokacija": "43.61, 16.48",
    "recenzija": 4.4,
    "postanski_broj": 21000,
    "vlasnici": [
      {
        "ime": "Marko",
        "prezime": "Cvetovski"
      }
    ]
  },
  {
    "naziv": "HGSPOT",
    "adresa": "Užarska ulica 18",
    "grad": "Rijeka",
    "drzava": "Hrvatska",
    "telefonski_broj": 51317475,
    "email": "rijeka@hgspot.hr",
    "geolokacija": "45.51, 14.42",
    "recenzija": 4.6,
    "postanski_broj": 51000,
    "vlasnici": [
      {
        "ime": "Saša",
        "prezime": "Lončar"
      },
      {
        "ime": "Vedrana",
        "prezime": "Lončar"
      }
    ]
  },
  {
    "naziv": "Svijet medija",
    "adresa": "Trg Drage Iblera 10",
    "grad": "Zagreb",
    "drzava": "Hrvatska",
    "telefonski_broj": 14554882,
    "email": "importanne.galleria@svijet-medija.hr",
    "geolokacija": "45.85, 16.00",
    "recenzija": 4.3,
    "postanski_broj": 10000,
    "vlasnici": [
      {
        "ime": "Anđelko",
        "prezime": "Ćurić"
      }
    ]
  },
  {
    "naziv": "Emmezeta",
    "adresa": "Ulica Siniše Glavaševića 1",
    "grad": "Zagreb",
    "drzava": "Hrvatska",
    "telefonski_broj": 72202022,
    "email": "info@emmezeta.hr",
    "geolokacija": "45.80, 16.05",
    "recenzija": 4.3,
    "postanski_broj": 10000,
    "vlasnici": [
      {
        "ime": "Andrzej",
        "prezime": "Pawel Sitarz"
      }
    ]
  },
  {
    "naziv": "Tehno Mag",
    "adresa": "Tehno Mag",
    "grad": "Zagreb",
    "drzava": "Hrvatska",
    "telefonski_broj": 15790602,
    "email": "webshop@tehno-mag.hr",
    "geolokacija": "45.81, 16.10",
    "recenzija": 4.3,
    "postanski_broj": 10000,
    "vlasnici": [
      {
        "ime": "Zlatko",
        "prezime": "Marošević"
      }
    ]
  },
  {
    "naziv": "Saturn",
    "adresa": "Alexanderplatz 3",
    "grad": "Berlin",
    "drzava": "Njemačka",
    "telefonski_broj": 4922122243333,
    "email": "shop@saturn.de",
    "geolokacija": "52.52, 13.41",
    "recenzija": 4.2,
    "postanski_broj": 10178,
    "vlasnici": [
      {
        "ime": "Karsten",
        "prezime": "Wildberger"
      }
    ]
  }
]
